"""empty message

Revision ID: 2dc16d063f98
Revises: 
Create Date: 2017-11-28 21:35:38.655746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc16d063f98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('firstName', sa.String(length=80), nullable=True),
    sa.Column('lastName', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('decliningBal', sa.Float(), nullable=True),
    sa.Column('mealSwipes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('storeName', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('storeName'),
    sa.UniqueConstraint('username')
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('vendor', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vendor'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('vendor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('vendor', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vendor'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meneu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['vendor'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemComponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('componentsID', sa.Integer(), nullable=True),
    sa.Column('itemID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['componentsID'], ['components.id'], ),
    sa.ForeignKeyConstraint(['itemID'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student', sa.Integer(), nullable=False),
    sa.Column('cook', sa.Integer(), nullable=True),
    sa.Column('inProgress', sa.Boolean(), nullable=True),
    sa.Column('isComplete', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('confirm', sa.Integer(), nullable=True),
    sa.Column('isFav', sa.Boolean(), nullable=True),
    sa.Column('isConfirm', sa.Boolean(), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cook'], ['cooks.id'], ),
    sa.ForeignKeyConstraint(['student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm')
    )
    op.create_index(op.f('ix_orders_timeStamp'), 'orders', ['timeStamp'], unique=False)
    op.create_table('orderItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=True),
    sa.Column('itemID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemID'], ['items.id'], ),
    sa.ForeignKeyConstraint(['orderID'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderItems')
    op.drop_index(op.f('ix_orders_timeStamp'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('itemComponents')
    op.drop_table('meneu_items')
    op.drop_table('items')
    op.drop_table('cooks')
    op.drop_table('components')
    op.drop_table('vendors')
    op.drop_table('students')
    # ### end Alembic commands ###
